version: '3'
services:
  mysql_maestro:
    image: mysql:5.7
    container_name: maestro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3310:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica

  mysql_esclavo:
    image: mysql:5.7
    container_name: esclavo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: "mysql_maestro,mysql_esclavo"
      PMA_PORT: 3306
