version: '3'
services:
  mysql_maestro:
    image: mysql
    container_name: maestro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3310:3306"

  mysql_esclavo:
    image: mysql
    container_name: esclavo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: "mysql_maestro,mysql_esclavo"
      PMA_PORT: 3306
